version: '3'

volumes:
  dados:
  
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      #volume dos dados
      - dados:/var/lib/postgresql/data
      #scripts
      - ./scripts:/scripts
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html
      # cnfig proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes: 
      #aplicacao
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh